[package]
name = "leetcode-problems"
version = "0.1.0"
edition = "2021"
authors = ["ChrisShen93 <chrisshen93@gmail.com>"]

[dependencies]
reqwest = { version = "0.11.24" }

[lib]
doctest = false
test = true
